In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [66]:
df=pd.read_csv('adult.csv')
df.head(10)

39          State-gov   77516      Bachelors   13           Never-married  \
0  50   Self-emp-not-inc   83311      Bachelors   13      Married-civ-spouse   
1  38            Private  215646        HS-grad    9                Divorced   
2  53            Private  234721           11th    7      Married-civ-spouse   
3  28            Private  338409      Bachelors   13      Married-civ-spouse   
4  37            Private  284582        Masters   14      Married-civ-spouse   
5  49            Private  160187            9th    5   Married-spouse-absent   
6  52   Self-emp-not-inc  209642        HS-grad    9      Married-civ-spouse   
7  31            Private   45781        Masters   14           Never-married   
8  42            Private  159449      Bachelors   13      Married-civ-spouse   
9  37            Private  280464   Some-college   10      Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   
5       Other-service   Not-in-family   Black   Female      0   0   16   
6     Exec-managerial         Husband   White     Male      0   0   45   
7      Prof-specialty   Not-in-family   White   Female  14084   0   50   
8     Exec-managerial         Husband   White     Male   5178   0   40   
9     Exec-managerial         Husband   Black     Male      0   0   80   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K  
5         Jamaica   <=50K  
6   United-States    >50K  
7   United-States    >50K  
8   United-States    >50K  
9   United-States    >50K

In [67]:
df.shape

(32560, 15)

In [68]:
df.dtypes

39                 int64
 State-gov        object
 77516             int64
 Bachelors        object
 13                int64
 Never-married    object
 Adm-clerical     object
 Not-in-family    object
 White            object
 Male             object
 2174              int64
 0                 int64
 40                int64
 United-States    object
 <=50K            object
dtype: object

In [69]:
df.rename({'39':'age',' State-gov':'Workclass',' 77516':'fnlwgt',' Bachelors':'Education',' 13':'education_num',' Never-married':'marital_status',' Adm-clerical':'occupation',' Not-in-family':'relationship',' White':'race',' Male':'sex',' 2174':'capital_gain',' 0':'capital_loss',' 40':'hours_per_week',' United-States':'native_country',' <=50K':'income'},axis=1,inplace=True)
df.dtypes

age                int64
Workclass         object
fnlwgt             int64
Education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [70]:
df.head(10)

age          Workclass  fnlwgt      Education  education_num  \
0   50   Self-emp-not-inc   83311      Bachelors             13   
1   38            Private  215646        HS-grad              9   
2   53            Private  234721           11th              7   
3   28            Private  338409      Bachelors             13   
4   37            Private  284582        Masters             14   
5   49            Private  160187            9th              5   
6   52   Self-emp-not-inc  209642        HS-grad              9   
7   31            Private   45781        Masters             14   
8   42            Private  159449      Bachelors             13   
9   37            Private  280464   Some-college             10   

           marital_status          occupation    relationship    race  \
0      Married-civ-spouse     Exec-managerial         Husband   White   
1                Divorced   Handlers-cleaners   Not-in-family   White   
2      Married-civ-spouse   Handlers-cleaners         Husband   Black   
3      Married-civ-spouse      Prof-specialty            Wife   Black   
4      Married-civ-spouse     Exec-managerial            Wife   White   
5   Married-spouse-absent       Other-service   Not-in-family   Black   
6      Married-civ-spouse     Exec-managerial         Husband   White   
7           Never-married      Prof-specialty   Not-in-family   White   
8      Married-civ-spouse     Exec-managerial         Husband   White   
9      Married-civ-spouse     Exec-managerial         Husband   Black   

       sex  capital_gain  capital_loss  hours_per_week  native_country  income  
0     Male             0             0              13   United-States   <=50K  
1     Male             0             0              40   United-States   <=50K  
2     Male             0             0              40   United-States   <=50K  
3   Female             0             0              40            Cuba   <=50K  
4   Female             0             0              40   United-States   <=50K  
5   Female             0             0              16         Jamaica   <=50K  
6     Male             0             0              45   United-States    >50K  
7   Female         14084             0              50   United-States    >50K  
8     Male          5178             0              40   United-States    >50K  
9     Male             0             0              80   United-States    >50K

In [71]:
df.isnull().sum()

age               0
Workclass         0
fnlwgt            0
Education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [72]:
df['Education'].value_counts()

 HS-grad         10501
 Some-college     7291
 Bachelors        5354
 Masters          1723
 Assoc-voc        1382
 11th             1175
 Assoc-acdm       1067
 10th              933
 7th-8th           646
 Prof-school       576
 9th               514
 12th              433
 Doctorate         413
 5th-6th           333
 1st-4th           168
 Preschool          51
Name: Education, dtype: int64

In [73]:
df['Workclass'].value_counts()

 Private             22696
 Self-emp-not-inc     2541
 Local-gov            2093
 ?                    1836
 State-gov            1297
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
Name: Workclass, dtype: int64

In [74]:
df['marital_status'].value_counts()

 Married-civ-spouse       14976
 Never-married            10682
 Divorced                  4443
 Separated                 1025
 Widowed                    993
 Married-spouse-absent      418
 Married-AF-spouse           23
Name: marital_status, dtype: int64

In [75]:
df['occupation'].value_counts()

 Prof-specialty       4140
 Craft-repair         4099
 Exec-managerial      4066
 Adm-clerical         3769
 Sales                3650
 Other-service        3295
 Machine-op-inspct    2002
 ?                    1843
 Transport-moving     1597
 Handlers-cleaners    1370
 Farming-fishing       994
 Tech-support          928
 Protective-serv       649
 Priv-house-serv       149
 Armed-Forces            9
Name: occupation, dtype: int64

In [76]:
df['relationship'].value_counts()

 Husband           13193
 Not-in-family      8304
 Own-child          5068
 Unmarried          3446
 Wife               1568
 Other-relative      981
Name: relationship, dtype: int64

In [77]:
df['race'].value_counts()

 White                 27815
 Black                  3124
 Asian-Pac-Islander     1039
 Amer-Indian-Eskimo      311
 Other                   271
Name: race, dtype: int64

In [78]:
df['sex'].value_counts()

 Male      21789
 Female    10771
Name: sex, dtype: int64

In [79]:
df['native_country' ].value_counts()

 United-States                 29169
 Mexico                          643
 ?                               583
 Philippines                     198
 Germany                         137
 Canada                          121
 Puerto-Rico                     114
 El-Salvador                     106
 India                           100
 Cuba                             95
 England                          90
 Jamaica                          81
 South                            80
 China                            75
 Italy                            73
 Dominican-Republic               70
 Vietnam                          67
 Guatemala                        64
 Japan                            62
 Poland                           60
 Columbia                         59
 Taiwan                           51
 Haiti                            44
 Iran                             43
 Portugal                         37
 Nicaragua                        34
 Peru                             31
 

In [80]:
df['income'].value_counts()

 <=50K    24719
 >50K      7841
Name: income, dtype: int64

In [81]:
df['occupation'].value_counts()

 Prof-specialty       4140
 Craft-repair         4099
 Exec-managerial      4066
 Adm-clerical         3769
 Sales                3650
 Other-service        3295
 Machine-op-inspct    2002
 ?                    1843
 Transport-moving     1597
 Handlers-cleaners    1370
 Farming-fishing       994
 Tech-support          928
 Protective-serv       649
 Priv-house-serv       149
 Armed-Forces            9
Name: occupation, dtype: int64

In [82]:
df.duplicated().sum()

24

In [83]:
df.drop_duplicates(inplace=True)

In [84]:
df.dtypes

age                int64
Workclass         object
fnlwgt             int64
Education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [85]:
df['occupation'].value_counts()

 Prof-specialty       4136
 Craft-repair         4094
 Exec-managerial      4065
 Adm-clerical         3767
 Sales                3650
 Other-service        3291
 Machine-op-inspct    2000
 ?                    1843
 Transport-moving     1597
 Handlers-cleaners    1369
 Farming-fishing       992
 Tech-support          927
 Protective-serv       649
 Priv-house-serv       147
 Armed-Forces            9
Name: occupation, dtype: int64

In [86]:
from sklearn.preprocessing import LabelEncoder

In [87]:
lb = LabelEncoder()
df['Workclass'] = lb.fit_transform(df['Workclass'])
df['occupation'] = lb.fit_transform(df['occupation'])
df['Education'] = lb.fit_transform(df['Education'])
df['marital_status'] = lb.fit_transform(df['marital_status'])
df['relationship'] = lb.fit_transform(df['relationship'])
df['sex'] = lb.fit_transform(df['sex'])
df['income'] = lb.fit_transform(df['income'])
df['native_country'] = lb.fit_transform(df['native_country'])
df['race'] = lb.fit_transform(df['race'])

In [88]:
df.dtypes


age               int64
Workclass         int64
fnlwgt            int64
Education         int64
education_num     int64
marital_status    int64
occupation        int64
relationship      int64
race              int64
sex               int64
capital_gain      int64
capital_loss      int64
hours_per_week    int64
native_country    int64
income            int64
dtype: object

In [89]:
df.drop(['education_num','fnlwgt','marital_status','relationship','race','capital_loss','capital_gain'],axis=1,inplace=True)

In [90]:
df['Education'].value_counts()

11    10494
15     7282
9      5352
12     1722
8      1382
1      1175
7      1067
0       933
5       645
14      576
6       514
2       433
10      413
4       332
3       166
13       50
Name: Education, dtype: int64

In [91]:
x=df.iloc[:,:-1]
y=df['income']
print(type(x))
print(type(y))


<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [92]:
x.shape


(32536, 7)

In [93]:
y.shape

(32536,)

In [94]:
from sklearn.model_selection import train_test_split

In [95]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(24402, 7)
(8134, 7)
(24402,)
(8134,)


In [96]:
x_train.head()

age  Workclass  Education  occupation  sex  hours_per_week  \
9537    52          2         11           3    1              40   
21346   30          4          9          10    1              35   
21183   25          2         15           1    0              35   
22959   21          4         11           7    1               1   
30482   20          4          4           6    1              30   

       native_country  
9537               39  
21346              39  
21183              39  
22959              39  
30482              13

In [97]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,classification_report


In [98]:
def classifier(model,x_test,x_train,y_test,y_train):
    model.fit(x_train,y_train)
    print("stats of model",model)
    print("training_score:",model.score(x_train,y_train))
    print("testing_score:",model.score(x_test,y_test))
    Y_pred=model.predict(x_test)
    print("predictions:-\n",Y_pred)
    cm=confusion_matrix(y_test,Y_pred)
    print("confusion matrix:-\n",cm)
    cr=classification_report(y_test,Y_pred)
    print("classification Report:-\n",cr)
    mc=((cm[0][1]+cm[1][0])/(cm[0][1]+cm[1][0]+cm[1][1]+cm[0][0]))*100
    print("misclassification percentage :-",mc)

In [99]:
m1=KNeighborsClassifier(n_neighbors=10)
classifier(m1,x_test,x_train,y_test,y_train)


stats of model KNeighborsClassifier(n_neighbors=10)
training_score: 0.8182116219981969
testing_score: 0.7784607819031227
predictions:-
 [0 0 0 ... 0 0 0]
confusion matrix:-
 [[5658  540]
 [1262  674]]
classification Report:-
               precision    recall  f1-score   support

           0       0.82      0.91      0.86      6198
           1       0.56      0.35      0.43      1936

    accuracy                           0.78      8134
   macro avg       0.69      0.63      0.65      8134
weighted avg       0.76      0.78      0.76      8134

misclassification percentage :- 22.15392180968773


In [100]:
m2=LogisticRegression(solver='liblinear')
classifier(m2,x_test,x_train,y_test,y_train)

stats of model LogisticRegression(solver='liblinear')
training_score: 0.7595279075485616
testing_score: 0.7622326038849274
predictions:-
 [0 0 0 ... 0 0 1]
confusion matrix:-
 [[5893  305]
 [1629  307]]
classification Report:-
               precision    recall  f1-score   support

           0       0.78      0.95      0.86      6198
           1       0.50      0.16      0.24      1936

    accuracy                           0.76      8134
   macro avg       0.64      0.55      0.55      8134
weighted avg       0.72      0.76      0.71      8134

misclassification percentage :- 23.776739611507253


In [101]:
m3=DecisionTreeClassifier(criterion='entropy',max_depth=8,min_samples_split=12)
classifier(m3,x_test,x_train,y_test,y_train)

stats of model DecisionTreeClassifier(criterion='entropy', max_depth=8, min_samples_split=12)
training_score: 0.8040734366035571
testing_score: 0.8057536267519055
predictions:-
 [0 0 0 ... 0 0 1]
confusion matrix:-
 [[5718  480]
 [1100  836]]
classification Report:-
               precision    recall  f1-score   support

           0       0.84      0.92      0.88      6198
           1       0.64      0.43      0.51      1936

    accuracy                           0.81      8134
   macro avg       0.74      0.68      0.70      8134
weighted avg       0.79      0.81      0.79      8134

misclassification percentage :- 19.424637324809442


In [102]:
m4=RandomForestClassifier(n_estimators=80,criterion='gini',max_depth=9,min_samples_split=12)
classifier(m4,x_test,x_train,y_test,y_train)

stats of model RandomForestClassifier(max_depth=9, min_samples_split=12, n_estimators=80)
training_score: 0.819932792394066
testing_score: 0.8146053602163758
predictions:-
 [0 0 0 ... 0 0 1]
confusion matrix:-
 [[5844  354]
 [1154  782]]
classification Report:-
               precision    recall  f1-score   support

           0       0.84      0.94      0.89      6198
           1       0.69      0.40      0.51      1936

    accuracy                           0.81      8134
   macro avg       0.76      0.67      0.70      8134
weighted avg       0.80      0.81      0.80      8134

misclassification percentage :- 18.53946397836243


In [103]:
m5 = SVC(kernel='linear',C=1)
classifier(m5,x_test,x_train,y_test,y_train)

stats of model SVC(C=1, kernel='linear')
training_score: 0.7580935988853372
testing_score: 0.7619867223998033
predictions:-
 [0 0 0 ... 0 0 0]
confusion matrix:-
 [[6198    0]
 [1936    0]]
classification Report:-
               precision    recall  f1-score   support

           0       0.76      1.00      0.86      6198
           1       0.00      0.00      0.00      1936

    accuracy                           0.76      8134
   macro avg       0.38      0.50      0.43      8134
weighted avg       0.58      0.76      0.66      8134

misclassification percentage :- 23.80132776001967


/Applications/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Applications/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Applications/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
